### ISSUE TITLE
Search for proposition filtering by author

### ISSUE THREAD

**Issue by BrunaNayara** [AcompanhaLegis/camara-data-portal#10]
# Problem
Currently, when searching for propositions there are filters - type, number, year, presentation, theme. Another good filter would be the author of the proposition.

The screenshots below show the propositions page. 
![screenshot of the propositions page. There is a sidebar on the left. In the main section of the page, there are the filters on the top with a search button. Below that, there is a list of the propositions with their code (type, number and year), abstract and buttons to "see more", "favorite", "update"](https://user-images.githubusercontent.com/4125846/94375151-facb3980-00e7-11eb-9352-261a23b08373.png)

# Solution
Create the author filter.

## Tasks
- [ ] Create the filter
- [ ] Filter list results

**Comment by Benjur274** [comment]
Hi, can i work on this issue ? Thank you.

**Comment by Benjur274** [comment]
Hi, can i work on this issue ? Thank you. @BrunaNayara

**Comment by BrunaNayara** [comment]
@Benjur274 Yes, please!
If you need anything to help you work on this, please reach out and we'll try to help you :D

**Comment by kimuraz** [comment]
@Benjur274 still interested on working on this one?
