### ISSUE TITLE
Remove auth from non-api features

### ISSUE THREAD

**Issue by kimuraz** [AcompanhaLegis/camara-data-portal#14]
## Problem

:gb: We have Open Data (from Camara dos Deputados) mixed with data that comes from our own API. The open data shouldn't be restricted by our auth system.

:brazil: Temos dados abertos (vindos da Camara dos Deputados) misturados com dados que vem da API. Os dados abertos não deveriam ser restringidos pelo nosso sistema de autenticação. 

## Solution

:gb: Restrict visibility from pages and components (button, links, etc) that need interaction with our API and refactor the dashboard pages to remove the login need.

:brazil: Restringir visibilidade de páginas e componentes (botões, links, etc) que necessitem interação com nossa API e refatorar as páginas de dashboard para que não haja necessidade de login.

**Comment by fcgomes92** [comment]
Hey (:
Can I pick this issue?

**Comment by BrunaNayara** [comment]
@fcgomes92 yes, please! If you work on this, please, let us know. Anything you want to ask, please come to us :D
