### ISSUE TITLE
Improve a11y on homepage

### ISSUE THREAD

**Issue by kimuraz** [AcompanhaLegis/camara-data-portal#16]
# :brazil: Melhorar acessibilidade na página inicial

## Problem / Problema

:gb: According to lighthouse analysis:

:brazil: De acordo com a análise do lighthouse:

![image](https://user-images.githubusercontent.com/9062864/94746182-780edc80-037c-11eb-93a0-49f9f8ffb1be.png)

## Solution / Solução

* :gb: Add `lang` attribute to html tag / :brazil: Adicionar atributo `lang` na tag html

* :gb: Add `alt` attribute to image / :brazil: Adicionar atributo `alt` na imagem

> Note/Nota: Leave the background color issue to a next phase. / Deixar a cor de fundo para uma próxima fase.

**Comment by 29parthi** [comment]
Can I pick this issue?

**Comment by 29parthi** [comment]
added 
e7b45e8 for this issue

**Comment by kimuraz** [comment]
New home page:

![image](https://user-images.githubusercontent.com/9062864/148660146-2bb5962e-fb33-4663-aedc-b236d81b2a55.png)

Let's close this issue when we reach at least 90 score on lighthouse
