### ISSUE TITLE
Update reset password request URL on /profile

### ISSUE THREAD

**Issue by kimuraz** [AcompanhaLegis/camara-data-portal#17]
# :brazil: Atualizar URL do request de mudar a senha no /profile

:gb: The URL `reset_password` changed to `change_password`, here in the frontend it needs to be updated.

:brazil: A URL `reset_password` mudou para `change_password`, aqui no frontend ela precisa ser atualizada.

## Due to / Devido a:

https://github.com/AcompanhaLegis/acompanha-legis-api/issues/4

https://github.com/AcompanhaLegis/acompanha-legis-api/pull/9

## Solution / Solução:

:gb: On `/profile` page, update the API request to the new endpoint.

:brazil: Na página `/profile`, atualizar o request feito para API para o novo endpoint.

**Comment by 29parthi** [comment]
Can you assign it to me?

**Comment by kimuraz** [comment]
@29parthi Sure!
