### ISSUE TITLE
Improve UI of favorites

### ISSUE THREAD

**Issue by BrunaNayara** [AcompanhaLegis/camara-data-portal#5]
# Problem
Currently, the favorites are shown in the sidebar. And as the favorites grow, this list grow and it makes it more difficult to find an specific favorite. 
The screenshots below show the page, with the favorites open in the sidebar.
![screenshot of the propositions page. The sidebar has a "favorites" option that opens a "propositions" option with 4 favorites](https://user-images.githubusercontent.com/4125846/94375151-facb3980-00e7-11eb-9352-261a23b08373.png)

![ screenshot of the favorites in the sidebar. The sidebar has a "favorites" option that opens a "propositions" option with 4 favorites](https://user-images.githubusercontent.com/4125846/94375215-77f6ae80-00e8-11eb-8f9a-cc1ab74dfb28.png)

# Solution
The general idea is to propose a different UI for the favorites. Feel free to mockup or sketch any idea and bring the discussion.

## Tasks
- [ ] Propose solution
- [ ] Implement solution

**Comment by kimuraz** [comment]
Suggestion / sugestāo:

:gb: Add a component (use ant-design) like this near the profile on the right top corner:

🇧🇷 Adicionar um componente parecido com esse (usando o ant-design) próximo do profile no canto direito superior:

![image](https://user-images.githubusercontent.com/9062864/96876470-cba2b080-1478-11eb-9909-7a039310baaa.png)
