### ISSUE TITLE
Create breadcrumbs

### ISSUE THREAD

**Issue by BrunaNayara** [AcompanhaLegis/camara-data-portal#7]
# Problem
Currently, there are no breadcrumbs or elements that help the navigation within the site.

# Solution
The expected solution is to have breadcrumbs.

## Tasks
- [ ] Implement breadcrumbs

**Comment by fcgomes92** [comment]
Hey (:

I have an idea for this feature.

What do you think about this breadcrumbs layout?

![Peek 2020-10-10 15-35](https://user-images.githubusercontent.com/6561278/95662560-3285a880-0b0e-11eb-8f1b-5598a2a9ce23.gif)

**Comment by fcgomes92** [comment]
I've added a PR request w/ the code to this feature in case this is the desired behavior (:

**Comment by BrunaNayara** [comment]
I think it is very nice. I will look into the PR. 
Sorry for the late response

**Comment by kimuraz** [comment]
Solved on https://github.com/AcompanhaLegis/camara-data-portal/pull/28
