### ISSUE TITLE
Fix cards of participants of an event

### ISSUE THREAD

**Issue by BrunaNayara** [AcompanhaLegis/camara-data-portal#9]
# Problem
When you go to the calendar page, click on an event, you can see the participants of that event. There are cards that show them. Some of them are with the link button in the wrong place (it's just a bit up). They should be on the bottom of the card.
 
The screenshot below shows 4 cards of the participants of an specific event. The only one that is correct is the second
![screenshot of the 4 cards.](https://user-images.githubusercontent.com/4125846/94375639-75498880-00eb-11eb-9c02-f9019358ef1b.png)

# Solution

## Tasks
- [ ] lorem ipsum

**Comment by Tawliew** [comment]
Hi! Can I try to fix this one?

**Comment by brendamoreira** [comment]
Sure!

**Comment by Tawliew** [comment]
sorry, but I'm kind of busy and I can't fix this right now :(

**Comment by brendamoreira** [comment]
No problem. Thanks for the interest (:

**Comment by kimuraz** [comment]
Fixed by #43
